### ISSUE TITLE
sampling from univariate conditionals

### ISSUE THREAD

**Issue by martinjankowiak** [dargilboa/mdma#12]
hello,

congrats on the interesting work/package! i am interested in trying your approach to:

1. fit a density model, say `p(x_1, x_2, x_3, x_4)`

and

2. sample from univariate conditionals like `p(x_2 | x_1, x_3, x_4)`

however, i'm at bit confused about the API. how can i go about doing this?

thanks!

**Comment by tvatter** [comment]
Hi @martinjankowiak,

Thanks a lot for your interest in the paper and the interesting question:

- @aripakman derived the equations, the sampling algo described in our Section 3.5 can be adapted from univariate conditionals. Please don't hesitate to reach out via email if you want a draft. 

- @dargilboa implemented it and it is available in the repo, but the API isn't documented yet as we just noticed a small numerical issue that we want to fix. We'll be sure to ping you again shortly!

**Comment by tvatter** [comment]
@aripakman and @dargilboa don't hesitate to correct me if I missed something :)

**Comment by dargilboa** [comment]
I would just add that the approach isn't limited to univariate conditionals, and also avoids the linear scaling with d of standard autoregressive sampling. We hope to release the updated version soon.

**Comment by dargilboa** [comment]
Hi @martinjankowiak, conditional sampling is now implemented by supplying the cond_inds and cond_X arguments to the sample function, which specify the variables to condition on and the conditional values respectively.

**Comment by martinjankowiak** [comment]
@dargilboa thanks for pinging me! i will definitely give it a try when i have the time.
